"use client";

import { cn } from "@/lib/utils";
import { ShieldAlert, Download } from "lucide-react";

interface ToxicLink {
  url: string;
  score: number;
  reason: string;
}

interface ToxicAnalysis {
  total: number;
  toxic: ToxicLink[];
  suspect: ToxicLink[];
  clean: number;
}

interface ToxicScoreProps {
  analysis: ToxicAnalysis;
}

function ScoreBar({ score }: { score: number }) {
  const color =
    score >= 60 ? "bg-red-500" : score >= 30 ? "bg-yellow-500" : "bg-green-500";
  return (
    <div className="flex items-center gap-2">
      <div className="h-2 w-20 rounded-full bg-zinc-200">
        <div
          className={cn("h-2 rounded-full", color)}
          style={{ width: `${score}%` }}
        />
      </div>
      <span className="text-xs font-medium text-zinc-600">{score}</span>
    </div>
  );
}

export function ToxicScore({ analysis }: ToxicScoreProps) {
  const circles = [
    {
      label: "Toxic",
      count: analysis.toxic.length,
      color: "bg-red-500",
      ring: "ring-red-200",
    },
    {
      label: "Suspect",
      count: analysis.suspect.length,
      color: "bg-yellow-500",
      ring: "ring-yellow-200",
    },
    {
      label: "Clean",
      count: analysis.clean,
      color: "bg-green-500",
      ring: "ring-green-200",
    },
  ];

  const handleDownloadDisavow = () => {
    const lines = analysis.toxic.map((link) => `domain:${new URL(link.url).hostname}`);
    const content = `# Disavow file generated by Orisoy SEO Suite\n# Total toxic links: ${analysis.toxic.length}\n\n${lines.join("\n")}`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "disavow.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="rounded-lg border border-zinc-200 bg-white p-6 space-y-6">
      <div className="flex items-center gap-2">
        <ShieldAlert className="h-5 w-5 text-red-600" />
        <h3 className="text-sm font-semibold text-zinc-700">
          Toxic Link Analysis
        </h3>
        <span className="ml-auto text-xs text-zinc-400">
          {analysis.total} total links
        </span>
      </div>

      <div className="flex items-center justify-center gap-8">
        {circles.map((c) => (
          <div key={c.label} className="flex flex-col items-center gap-2">
            <div
              className={cn(
                "flex h-16 w-16 items-center justify-center rounded-full ring-4",
                c.color,
                c.ring
              )}
            >
              <span className="text-lg font-bold text-white">{c.count}</span>
            </div>
            <span className="text-xs font-medium text-zinc-500">{c.label}</span>
          </div>
        ))}
      </div>

      {analysis.toxic.length > 0 && (
        <div className="space-y-2">
          <h4 className="text-xs font-medium text-zinc-500">Toxic Links</h4>
          <div className="space-y-2">
            {analysis.toxic.map((link, i) => (
              <div
                key={i}
                className="flex items-center gap-3 rounded-md border border-red-100 bg-red-50 px-3 py-2"
              >
                <div className="min-w-0 flex-1">
                  <p className="truncate text-sm font-medium text-zinc-900">
                    {link.url}
                  </p>
                  <p className="text-xs text-zinc-500">{link.reason}</p>
                </div>
                <ScoreBar score={link.score} />
              </div>
            ))}
          </div>
        </div>
      )}

      {analysis.suspect.length > 0 && (
        <div className="space-y-2">
          <h4 className="text-xs font-medium text-zinc-500">Suspect Links</h4>
          <div className="space-y-2">
            {analysis.suspect.map((link, i) => (
              <div
                key={i}
                className="flex items-center gap-3 rounded-md border border-yellow-100 bg-yellow-50 px-3 py-2"
              >
                <div className="min-w-0 flex-1">
                  <p className="truncate text-sm font-medium text-zinc-900">
                    {link.url}
                  </p>
                  <p className="text-xs text-zinc-500">{link.reason}</p>
                </div>
                <ScoreBar score={link.score} />
              </div>
            ))}
          </div>
        </div>
      )}

      <button
        onClick={handleDownloadDisavow}
        disabled={analysis.toxic.length === 0}
        className={cn(
          "flex w-full items-center justify-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors",
          analysis.toxic.length > 0
            ? "bg-red-600 text-white hover:bg-red-700"
            : "cursor-not-allowed bg-zinc-100 text-zinc-400"
        )}
      >
        <Download className="h-4 w-4" />
        Download Disavow File
      </button>
    </div>
  );
}
